config/routes.rb
YoungEmpowered::Application.routes.draw do
resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end
 
match '/new', to: 'inquiries#new', via: 'get'

  root'young_empowered#home'   #get "young_empowered/home" 
  match '/activitiesandvolunteer', to: 'young_empowered#activitiesandvolunteer', via: 'get'  #get "young_empowered/Activities_and_Volunteer"
  match '/contact', to: 'young_empowered#contact', via: 'get'
  match '/about', to: 'young_empowered#about', via: 'get'
   match '/project1', to: 'young_empowered#project1', via: 'get'
   match '/project2', to: 'young_empowered#project2', via: 'get'
   match '/project3', to: 'young_empowered#project3', via: 'get'
   match '/project4', to: 'young_empowered#project4', via: 'get'
   match '/project5', to: 'young_empowered#project5', via: 'get'
   match '/join_us', to: 'young_empowered#join_us', via: 'get'
   match '/newsandevents', to: 'young_empowered#newsandevents', via: 'get'
   match '/stories', to: 'young_empowered#stories', via: 'get'

  

end

app/models/inquiry.rb
class Inquiry
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations 
  include ActionView::Helpers::TextHelper
  
  attr_accessor :name, :email, :message #, :nickname
  
  validates :name, 
            :presence => true
  
  validates :email,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
  
 validates :message,
            :length => { :minimum => 10, :maximum => 1000 }
            
 #  validates :nickname, 
 #           :format => { :with => /^$/ }
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def deliver
    return false unless valid?
    Pony.mail({
      :from => %("#{name}" <#{email}>),
      :reply_to => email,
      :subject => "Website inquiry",
      :body => message,
      :html_body => simple_format(message)
    })
  end
      
  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  
  def new
    @inquiry = Inquiry.new
  end
    
  def create
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.deliver
      render :thank_you
    else
      render :new
    end
  end
  
end

app/controllers/young_empowered_controller.rb
class YoungEmpoweredController < ApplicationController
 

  def home
  end

  def Activities_and_Volunteer
  end

  def contact  	
  end

  def about
  end

  def stories
  end

  def newsandevents
  end

  def join_us  	
  end

  def project1
  end

  def project2
  end

  def project3
  end

  def project4
  end

  def project5
  end
  
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/young_empowered_helper.rb
module YoungEmpoweredHelper
end

app/views/inquiries/_form.html.erb
<%= form_for inquiry, html: { class: "edit_post", id: "edit_post_45" } do |f| %>
  
  <% if inquiry.errors.any? %>
    <ul>
      <% inquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    
    </ul>
  <% end %>
  
  <div id:"label">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  
  <div>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  
 
    <%= f.label :message %><br/>
    <%= f.text_area :message %>
  
  
  <div>
    <%= f.submit "Send" , class: "btn btn-large btn-primary btn_send" %>
  </div>
<% end %>

app/views/inquiries/new.html.erb
<% provide(:title, 'Volantary') %>

<div class="center hero-unit">
  <div class="inline_center">

		<div class="slidepic volunatary_top_pic">

      		<%= image_tag("volunteer1111.jpg", alt: "volunteer", :id => "auto_resizeimage") %>
			<h3>BECOME A ROLE MODEL TODAY<br>
				AND LEAVE YOUR LEGACY IN THE WORLD
			</h3>
		</div>

		<div class="headline">
     	 <h1><%= link_to "Activities << ", activitiesandvolunteer_path %>Voluntary</h1>
  	  </div>

		<br><h4 id="header_voluntary">VOLUNTARY PROGRAM</h4>


   <div class="voluntary_left_column">

   		<div class="group_story_element_box">

       		<div class="inside_div_pic image_for_box voluntary_left_pic">
        		<%= image_tag("DSCF2513.png", alt: "africans", :id => "auto_resizeimage")  %>
       		</div>
       		<div class="inside_div_pic image_for_box voluntary_right_pic">
        		<%= image_tag("DSCF2529.png", alt: "africans", :id => "auto_resizeimage")  %>
       		</div>
          
       		<p>
		         Young adult volunteers work one-on-one with participants as a big brother or a big sister, giving participants someone they can turn to in order to deal with common cultural ills. The effects of corruption, polygamy, family dysfunction, and gender inequality affects children in ways that adults are often unaware. 

Group sessions are held to address the importance of maintaining physical health, specifically, awareness of HIV and AIDS. In many African families, the perception of the disease is that of shame, which causes families to avoid discussing the issue. BAGEP has a forum that provides awareness of available tests, information on healthy lifestyle habits, and an opportunity to openly discuss the disease. Our goal is to educate youth on prevention, early detection, and treatment of diseases like HIV and AIDS, as well as other sexually transmitted viruses.
   
      		</p> 
      	
      </div>

      	<div class="please_text">
	      	<p>Please fill out the form below and we'll get back to you shortly</p>
	      	<%= render 'form', :inquiry => @inquiry %>


    	</div>
    </div> 



    <div class="story_column colom_left right_colum">

   		<div class=" group_story_element_box">

       		<div class="all-div-box for_school_admin">
				<div class="head">
					<h4>FOR SCHOOL ADMINISTRATORS </h4>
				</div>
		
			
				<p>School administrators, are welcome to contact us for any inquiries. You can either fill out the form bellow or by calling this number 1 (240) 593 4462, Or by sending an email to  boysandgirlsempowermentprogram@gmail.com.	
				Also feel free to visit our <%= link_to "Contact",  contact_path %> page for more info. Thanks for your time.
				</P>
				

			</div>
		</div>
	</div>		

			

   

   	

   





    
    



<div style="clear: left; margin-bottom: 35em"></div>

</div>
</div>

app/views/inquiries/thank_you.html.erb
<% provide(:title, 'Thanks') %>

 
<div class="center hero-unit">
  <div class="inline_center">

		

<h1>Thank you!</h1>
<br>
<br>
<p>Your request has been sent someone will contact you as soon as possible.</p>
<h1> <%= link_to "Go Back to Voluntary Page", new_path %></h1>
	
	<div style="clear: left; margin-bottom: 1em"></div>
 
  </div>


</div>









app/views/layouts/_bottomproject.html.erb

  


<div style="clear: left; margin-bottom: 1em"></div>     	
  </div>

</div>





app/views/layouts/_myfooter.html.erb
<footer class="footer">
  <small>
    <a href="#">© 2013 BAGEP | Privacy Policy</a>
  </small>
  
  <nav>
    <ul id="social">

      <li><div class="fb-share-button" data-href="https://www.facebook.com/alama.tounkara" data-type="button_count">
        </div>
      </li>
      
      <li >    
        <style>.ig-b- { display: inline-block; }
          .ig-b- img { visibility: hidden; }
          .ig-b-:hover { background-position: 0 -60px; } .ig-b-:active { background-position: 0 -120px; }
          .ig-b-v-24 { width: 137px; height: 24px; background: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24.png) no-repeat 0 0; }
          @media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
          .ig-b-v-24 { background-image: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24@2x.png); background-size: 160px 178px; } }
        </style>
        <a href="http://instagram.com/myambitionas?ref=badge" class="ig-b- ig-b-v-24"><img src="//badges.instagram.com/static/images/ig-badge-view-24.png" alt="Instagram" />
        </a>
      </li>

      <li>
        <a href="https://twitter.com/alama_al" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow us</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
        </script>
      </li>   
    </ul>

    <ul id="about_contact_others">
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <!--<li><a href="newsandevents">News</a></li>-->
    </ul>
  </nav>
  <div id="email_phone"><h3> Call: 1 (240) 593 4462 for more infomation </h3></div>
</footer>




app/views/layouts/_myheader.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "BAGEP", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",   root_path %></li>
              <li><%= link_to "About Us", about_path %></li>
              <li><%= link_to "Activities and Volunteers", activitiesandvolunteer_path %>
                <ul>
                 <li><a href="join_us">Stay Connected</a></li>
                 <li><a href="new">Voluntary</a></li>
                 <!--<li><a href="project1">Current Projects</a></li>
                 <li><a href="newsandevents">News&Event</a></li>
                 
                 <li><a href="stories">Succesful Stories</a></li>
               -->
                </ul>
             </li> 
              <li><%= link_to "Contact", contact_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->


app/views/layouts/_slidedown.html.erb
<h1 align="center">JQuery Sliding Menu Demo</h1>
    
    
   
    <ul class="parent">
      <li>
          <a href="#" class="slide">Title One</a>
            
            <ul class="child">
              <li><a href="#">Link One</a></li>
                <li><a href="#">Link Two</a></li>
                <li><a href="#">Link Three</a></li>
                <li><a href="#">Link Four</a></li>
                <li><a href="#">Link Five</a></li>
            </ul>
            
         </li>
    </ul>

    <ul class="parent">
      <li>
          <a href="#" class="slide">Title Two</a>
            
            <ul class="child">
              <li><a href="#">Link One</a></li>
                <li><a href="#">Link Two</a></li>
                <li><a href="#">Link Three</a></li>
                <li><a href="#">Link Four</a></li>
                <li><a href="#">Link Five</a></li>
            </ul>
            
         </li>
    </ul>
    
    <ul class="parent">
      <li>
          <a href="#" class="slide">Title Three</a>
            
            <ul class="child">
              <li><a href="#">Link One</a></li>
                <li><a href="#">Link Two</a></li>
                <li><a href="#">Link Three</a></li>
                <li><a href="#">Link Four</a></li>
                <li><a href="#">Link Five</a></li>
            </ul>
            
         </li>
    </ul>
    
    <ul class="parent">
      <li>
          <a href="#" class="slide">Title Four</a>
            
            <ul class="child">
              <li><a href="#">Link One</a></li>
                <li><a href="#">Link Two</a></li>
                <li><a href="#">Link Three</a></li>
                <li><a href="#">Link Four</a></li>
                <li><a href="#">Link Five</a></li>
            </ul>
            
         </li>
    </ul>
    
    <ul class="parent">
      <li>
          <a href="#" class="slide">Title Five</a>
            
            <ul class="child">
              <li><a href="#">Link One</a></li>
                <li><a href="#">Link Two</a></li>
                <li><a href="#">Link Three</a></li>
                <li><a href="#">Link Four</a></li>
                <li><a href="#">Link Five</a></li>
            </ul>
            
         </li>
    </ul>



<br /><br /><br />
  
    <br /><br />
    <!--<hr width="750" />-->
    <p align="center">
      Back to <a href="http://sarfraznawaz.wordpress.com/" style="color:#FF0066; font-weight:bold; text-decoration:none;">Sarfraz Ahmed's Blog</a>

  

app/views/layouts/_topproject.html.erb

<% provide(:title, 'PROJECTS') %>

<div class="center hero-unit">
	<div class="headline"> 

    <div class="headline dropdown_goback_activities">
      <h1><%= link_to "Activities << ", activitiesandvolunteer_path %>PROJECTS</h1>
    </div>
  
	<div class="all-div-box projectlist">
   
       
  
      

       <ul>
        <li ><div class="head"><h4>CURRENT PROJECTS</h4></div></li>


         <li><a href="project1">Project1</a></li>
         <li><a href="project2">Project2</a></li>
         <li><a href="project3">Project3</a></li>
         <li><a href="project4">Project4</a></li>
         <li><a href="project5">Project5</a></li>
        </ul>
      </div>
  </div>
  <div id="projectbody">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Empowerement Program For Young Africans | <%= yield(:title) %></title>
  
 <%= stylesheet_link_tag    "application", media: "all", 
  "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
      
    

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>




</head>


<body>



	<%= render 'layouts/myheader' %>


    <div class="container">
      <%= yield %>
    </div>

	<%= render 'layouts/myfooter' %>
 

  </body>
</html>

app/views/young_empowered/about.html.erb
<% provide(:title, 'About') %>

<div class="center hero-unit">
  <div class="inline_center">

		
    <div class="slidepic">
      <%= image_tag("Photo1181.png", alt: "crying", :id => "auto_resizeimage") %>
    </div>

		
    <div class="headline">
      <h1> <%= link_to "HOME<<", root_path %>ABOUT</h1>
    </div>

	  <table id="about_tables"> 
     <col  width: 50em" />
     <caption  class="about">WORKSHOPS</caption>





                

      <tr class="whitespace"> 
        <td class="leftelement"><BR>

          <p> 
            As an instrument for change, BAGEP holds motivational workshops so that children understand that they are the future of the country. By getting youth involved on a grassroots level, participants will be empowered to make a difference in the future. Participants are inspired to become leaders, entrepreneurs, and business owners in their community; to advocate for the equality of men and women in society; and learn that the decisions of each of us affects all of us in one way or another.
		      </P>

        </td> 
  
     <td class="rightelement"><%= image_tag("slideshow/569pxafricamapbs8.jpg", alt: "crying", :id => "gauto_resizeimage") %>  </td>  
      </tr>
   </table> 

       

 	  <table id="about_tables">

      	  <caption  id="about">What We do</caption>


       	<tr class="whitespace"> 
          <td class="leftelement"><BR>
          <p>
            BAGEP provides youth participants with mentors, tutors, and workshops to facilitate personal growth; and organized activities, which mainly focus on improving the health and aesthetics of residential communities, like greening projects that teach the benefits of proper trash disposal, recycling, and landscaping.
          </P>

         </td> 
          <td class="rightelement"><%= image_tag("africa/DSCF2543.png", alt: "crying", :id => "auto_resizeimage") %>  </td>  
    	</tr>
   	</table>


    <!--<table id="about_tables">

          <caption  id="about">Our Main Sponsors</caption>


          <tr class="whitespace"> 
          <td class="leftelement"><p> 
            <ul>
               <li>Microsoft</li>
               <li>Coca Cola</li>
               <li>Nike</li>
               <li>Addidas</li>
               <li>Honda</li>
            </ul>
            <p> Thanks to all of these companies our mission is going really smooth
              aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
              aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
              aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
              aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</p>
		  </P></td>  

          <td class="rightelement"> <%= image_tag("slideshow/49c3c8a00.jpg", alt: "crying", :id => "auto_resizeimage") %> </td>
      </tr>
    </table>
  -->

  <!--
  	<table id="about_tables">
     <caption  id="about">ORGANIZED ACTIVITIES</caption>





      <tr class="whitespace"> 
        <td class="leftelement"><BR>
          <p>
            A BAGEP leader gathers youth participants to conduct a neighborhood cleaning day. As part of the greening efforts, BAGEP gives the disposed plastic that is picked up and collected to a local recycling owner who exchanges them for trash cans to put into the neighborhoods. Clean neighborhoods provide a community resource where parks can be created on empty spaces to be used for outdoor ceremonies. Future efforts include implementing a Plant a Tree day to stop the advance of the desert and increase the frequency of rain. 

            Soccer games are organized to provide youth participants with physical recreation as well as learning to work as a team, developing competitive skills, and having fun.  
		      </P>
        </td> 
      <td class="rightelement"><%= image_tag("slideshow/youngaf.jpg", alt: "crying", :id => "auto_resizeimage") %>  </td>
      </tr>
    </table>
  -->


      
<div style="clear: left; margin-bottom: 1em"></div>

      
 
    </div>
</div>













app/views/young_empowered/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="center hero-unit">

  <div class="headline">
  <h1> <%= link_to "HOME<<", root_path %> <%= link_to "About<<", about_path %><%= link_to "Activities<<", activitiesandvolunteer_path %>Contact</h1>
</div>
 
 
  

      
    
        
 <div class="inside_div_pic contact_img">
        <%= image_tag("li_scaled_profile_picture.jpg", alt: "africans", :id => "auto_resizeimage") %>
      </div>
      <table id="contact_tables"> 
        <col  width: 50em" />
        <caption>Organizers</caption>
         
        

        <tr class="whitespace"> 
          <td class="leftelement"> Name:</td> 
          <td class="rightelement">Mamadou Dembele</td> 
        </tr> 

        <tr class="whitespace"> 
          <td class="leftelement">Email:</td> 
          <td class="rightelement">mmddembele@yahoo.com</td> 
        </tr>

        <tr class="whitespace"> 
          <td class="leftelement">Phone:</td> 
          <td class="rightelement">1 (240) 593 4462</td> 
        </tr>

        <tr class="whitespace">
          <td class="leftelement">Title:</td> 
          <td class="rightelement">CO-FOUNDER</td> 
        </tr>
        

      </table>


      
<div class="inside_div_pic contact_img">
        <%= image_tag("alama.png", alt: "IT", :id => "auto_resizeimage") %>
      </div>
     
      <table id="contact_tables"> 

       <caption>IT DEPARTEMENT</caption>
        

        <tr class="whitespace">
          <td class="leftelement">Email:</td> 
          <td class="rightelement">alama.tounkara@gmail.com</td> 
        </tr>

        <tr class="whitespace"> 
          <td class="leftelement">Phone:</td> 
          <td class="rightelement">1 (646) 750 7785</td> 
        </tr>      

      </table>
</div>


      
    

app/views/young_empowered/join_us.html.erb
<% provide(:title, 'JoinUs') %>

 
<div class="center hero-unit">
  <div class="inline_center">

    
    <div class="slidepic join_us_image">
      <%= image_tag("join.jpg", alt: "JoinUs" , :id => "auto_resizeimage") %>

          
      <h5>
        JOIN US         
      </h5>

    </div>

    <div class="headline dropdown_goback_activities">
      <h1><%= link_to "Activities << ", activitiesandvolunteer_path %>JOIN</h1>
    </div>
      
      <div class="join_intro">
     
        <br>
        <br>

        <p>
        
          Do you have a skill, expertise, or ideas you'd like to share in order to support BAGEP's mission? We'd love to have you join our team!  Contact           at               to discuss how you can help.

        </P>
        </div>

      <div class="fb-share-button circle_for_join_us facebook_join_circle" data-href="https://www.facebook.com/alama.tounkara" data-type="button_count">
        <a href="https://www.facebook.com/alama.tounkara" ,="" data-type="button_count">
          <%= image_tag("facebook-icon.jpg", alt: "facebook" , :id => "icons_image_circle") %>
        <h4> Join us on facebook</h4>
        </a>
       
      </div> 


     
      <div class="circle_for_join_us instangram_join_circle"> 
        <a href="http://instagram.com/myambitionas?ref=badge">
     <%= image_tag("intan-icon.jpg", alt:"instagram" , :id => "icons_image_circle") %>

         <h4> Follow us on instagram</h4>
        </a>
        
      </div>
      
      
      <div class="circle_for_join_us twitter_circle">
        <a href="https://twitter.com/alama_al" data-show-count="false" data-lang="en">
        <%= image_tag("Twitter icon round.jpg", alt:"twitter" , :id => "icons_image_circle") %>
          <h4> Follow us on twitter</h4>
        </a>
        
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
        </script>
      </div>

      

   

  

  
  

  <div style="clear: left; margin-bottom: 1em"></div>
 
  </div>


</div>